[package]
categories = ["config"]
description = "An unopinionated library for obtaining configuration, data, cache, & other directories"
documentation = "https://docs.rs/etcetera"
edition = "2018"
homepage = "https://github.com/lunacookies/etcetera"
keywords = ["xdg", "dirs", "directories", "basedir", "path", "folder", "directory", "app_dirs", "cli_dirs", "config"]
license = "MIT OR Apache-2.0"
name = "etcetera"
readme = "README.md"
repository = "https://github.com/lunacookies/etcetera"
version = "0.5.0"

[dependencies]
cfg-if = "1.0.0"
home = "0.5.4"
